### GET request with a header
#GET http://localhost:3000/users
#Accept: application/json

GET http://localhost:3000/users/61c455a73dd1a5427356a43b
#GET http://localhost:3000/users
Accept: application/json