### GET request with a header
#GET http://localhost:3000/tasks/
#Accept: application/json


#GET http://localhost:3000/tasks/61c4587e34091da234bbcb75
GET http://localhost:3000/tasks/
Accept: application/json