### Send POST request with json body
POST http://localhost:3000/users
Content-Type: application/json

{
  "age": 21,
  "email": "alala@season.com",
  "name": "A lot Winters",
  "password": "121212123"
}